In [175]:
import numpy as np
import matplotlib.pyplot as plt

In [176]:
X = np.array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
              [1, 1, 2, 1, 3, 0, 5, 10, 1, 2],
              [500, 700, 750, 600, 1450, 800, 1500, 2000, 450, 1000],
              [1, 1, 2, 1, 2, 1, 3, 3, 1, 2]], dtype = np.float64)
y = np.array([0, 0, 1, 0, 1, 0, 1, 0, 1, 1], dtype = np.float64)

In [177]:
def calc_std_feat(x):
    res = (x - x.mean()) / x.std()
    return res

# ДЗ №3 Гладышев В.В.

## Задание № 1

Измените функцию calc_logloss так, чтобы нули по возможности не попадали в np.log

In [178]:
X_st = X.copy()

In [179]:
X_st = X.copy()
X_st[1, :] = calc_std_feat(X[1, :])
X_st[2, :] = calc_std_feat(X[2, :])
X_st[3, :] = calc_std_feat(X[3, :])
X_st

array([[ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ],
       [-0.57142857, -0.57142857, -0.21428571, -0.57142857,  0.14285714,
        -0.92857143,  0.85714286,  2.64285714, -0.57142857, -0.21428571],
       [-0.97958969, -0.56713087, -0.46401617, -0.77336028,  0.97958969,
        -0.36090146,  1.08270439,  2.11385144, -1.08270439,  0.05155735],
       [-0.89625816, -0.89625816,  0.38411064, -0.89625816,  0.38411064,
        -0.89625816,  1.66447944,  1.66447944, -0.89625816,  0.38411064]])

In [180]:
def calc_logloss(y, y_pred):
    y_pred[y_pred == 0] = 1e-12
    y_pred[y_pred == 1] -= 1e-12

    err = - np.mean(y * np.log(y_pred) + (1.0 - y) * np.log(1.0 - y_pred))
    return err

In [181]:
def sigmoid(z):
    res = 1 / (1 + np.exp(-z))
    return res

In [184]:
def eval_model(X, y, iterations, alpha=1e-4):
    np.random.seed(42)
    W = np.random.randn(X.shape[0])
    n = X.shape[1]
    for i in range(1, iterations+1):
        z = np.dot(W, X)
        y_pred = sigmoid(z)
        err = calc_logloss(y, y_pred)
        W -= alpha * (1/n * np.dot((y_pred - y), X.T))
        if i % (iterations / 10) == 0:
            print("Итерация: {}\tW: {}\terr: {:.6f}".format(i, W, err))
    return W

In [185]:
W = eval_model(X_st, y, iterations=1000, alpha=1e-4)

Итерация: 100	W: [ 0.49635335 -0.14077362  0.64537112  1.52180639]	err: 0.762532
Итерация: 200	W: [ 0.49598986 -0.14327981  0.64305753  1.52058688]	err: 0.761207
Итерация: 300	W: [ 0.49562367 -0.14578284  0.64074779  1.51937134]	err: 0.759886
Итерация: 400	W: [ 0.49525481 -0.14828271  0.63844189  1.51815977]	err: 0.758569
Итерация: 500	W: [ 0.49488327 -0.15077942  0.63613984  1.51695219]	err: 0.757256
Итерация: 600	W: [ 0.49450906 -0.15327296  0.63384165  1.51574858]	err: 0.755947
Итерация: 700	W: [ 0.4941322  -0.15576332  0.63154733  1.51454897]	err: 0.754642
Итерация: 800	W: [ 0.49375269 -0.1582505   0.62925688  1.51335335]	err: 0.753342
Итерация: 900	W: [ 0.49337053 -0.16073448  0.62697031  1.51216173]	err: 0.752045
Итерация: 1000	W: [ 0.49298574 -0.16321527  0.62468762  1.51097412]	err: 0.750753


## Задание № 2

Подберите аргументы функции eval_model для логистической регрессии таким образом, чтобы log loss был минимальным

In [12]:
def eval_model_par(X, y, alpha=1e-4):
    np.random.seed(42)
    W = np.random.randn(X.shape[0])
    n = X.shape[1]
    i = 0
    delta = 1e-6
    err_prev = 0
    
    while True:
        z = np.dot(W, X)
        y_pred = sigmoid(z)
        err = calc_logloss(y, y_pred)
        W -= alpha * (1/n * np.dot((y_pred - y), X.T))
            
        if abs(err_prev - err) <= delta:
            return(i, W, err)
        else:
            err_prev = err
            i += 1
    return W

In [13]:
step_cnt = 1

for alpha in np.logspace(-5, -1, 9):
    i, W, err = eval_model_par(X_st, y, alpha)
    print("Шаг: {}\tИтераций: {}\talpha: {:.6f}\tW: {}\terr: {:.6f}".format(step_cnt, i, alpha, W, err))
    step_cnt += 1

Шаг: 1	Итераций: 81377	alpha: 0.000010	W: [ 0.45931561 -0.33152393  0.47222185  1.43688168]	err: 0.669050
Шаг: 2	Итераций: 91892	alpha: 0.000032	W: [ 0.32658539 -0.70380674  0.15826404  1.34825246]	err: 0.538843
Шаг: 3	Итераций: 54933	alpha: 0.000100	W: [ 0.19648124 -0.93993678 -0.00752236  1.4361401 ]	err: 0.494578
Шаг: 4	Итераций: 71451	alpha: 0.000316	W: [ 0.06852536 -1.58113243 -0.3376027   2.38089195]	err: 0.407093
Шаг: 5	Итераций: 61914	alpha: 0.001000	W: [ 0.22314951 -2.33287877 -0.81914792  3.72969277]	err: 0.337960
Шаг: 6	Итераций: 51918	alpha: 0.003162	W: [ 0.61139074 -3.18509484 -1.68624428  5.6661775 ]	err: 0.283801
Шаг: 7	Итераций: 62353	alpha: 0.010000	W: [ 1.80353219 -4.9997408  -4.03141577 10.49930837]	err: 0.208830
Шаг: 8	Итераций: 54804	alpha: 0.031623	W: [ 3.44560411 -7.64208554 -7.24124516 17.36693305]	err: 0.146626
Шаг: 9	Итераций: 38961	alpha: 0.100000	W: [  5.12953375 -10.52471566 -10.71446945  24.88051255]	err: 0.108765


## Задание № 3

Создайте функцию calc_pred_proba, возвращающую предсказанную вероятность класса 1 (на вход подаются W, который уже посчитан функцией eval_model и X, на выходе - массив y_pred_proba)

In [14]:
def calc_pred_proba(W, X):
    y_pred_proba = sigmoid(np.dot(W, X))
    return y_pred_proba

In [15]:
def eval_model_prb(X, y, iterations, alpha=1e-4):
    np.random.seed(42)
    W = np.random.randn(X.shape[0])
    n = X.shape[1]
    for i in range(1, iterations+1):
        y_pred = calc_pred_proba(W, X)
        err = calc_logloss(y, y_pred)
        W -= alpha * (1/n * np.dot((y_pred - y), X.T))
        if i % (iterations / 10) == 0:
            print("Итерация: {}\terr: {:.6f}\t\n\ty_pred_proba: {}\n".format(i, err, y_pred))

In [16]:
eval_model_prb(X_st, y, iterations=1000, alpha=1e-2)

Итерация: 100	err: 0.651970	
	y_pred_proba: [0.26077366 0.29704629 0.70512769 0.27854765 0.79761933 0.3455055
 0.95131371 0.94061238 0.25216695 0.74979548]

Итерация: 200	err: 0.577994	
	y_pred_proba: [0.31495285 0.33947089 0.71210905 0.32709382 0.74907425 0.39938268
 0.9215123  0.84967539 0.30897457 0.73979704]

Итерация: 300	err: 0.536174	
	y_pred_proba: [0.34871184 0.36283631 0.71567147 0.35574268 0.70753247 0.43121694
 0.89227804 0.7293736  0.34522073 0.73108419]

Итерация: 400	err: 0.513665	
	y_pred_proba: [0.36408686 0.37062051 0.7179813  0.36734759 0.6766449  0.44496732
 0.87078852 0.62383767 0.36246114 0.72504222]

Итерация: 500	err: 0.499922	
	y_pred_proba: [0.36763604 0.36892069 0.72032608 0.36827813 0.65516279 0.44756989
 0.85828839 0.54908563 0.36731517 0.72171447]

Итерация: 600	err: 0.489852	
	y_pred_proba: [0.36506226 0.3626048  0.72327136 0.36383264 0.64036554 0.44454173
 0.85259981 0.49885464 0.36567774 0.72060719]

Итерация: 700	err: 0.481507	
	y_pred_proba: [0.359842

In [17]:
calc_pred_proba(W, X_st)

array([0.34075722, 0.00618638, 1.        , 0.05367898, 0.93626047,
       0.02847029, 1.        , 0.01942685, 0.60942544, 0.99999992])

## Задание № 4

Создайте функцию calc_pred, возвращающую предсказанный класс (на вход подаются W, который уже посчитан функцией eval_model и X, на выходе - массив y_pred)

In [18]:
def calc_pred(W, X):
    y_pred_tmp = sigmoid(np.dot(W, X))
    y_pred = np.zeros(y_pred_tmp.shape[0]) 

    for i in range(y_pred_tmp.shape[0]):
        if (y_pred_tmp[i] > 0.5): 
            y_pred[i] = 1
        else:
            y_pred[i] = 0
    
    return y_pred

In [19]:
calc_pred(W, X_st)

array([0., 0., 1., 0., 1., 0., 1., 0., 1., 1.])

## Задание № 5

Посчитайте Accuracy, матрицу ошибок, точность и полноту, а также F1 score

In [89]:
y_pr = np.array([0, 1, 0, 0, 1, 1, 1, 0, 1, 1], dtype = np.float64)
y, y_pr

(array([0., 0., 1., 0., 1., 0., 1., 0., 1., 1.]),
 array([0., 1., 0., 0., 1., 1., 1., 0., 1., 1.]))

In [90]:
def Accuracy(y, y_pr):
    acc = 0
    for y_i, y_pr_i in zip(y, y_pr):
        if y_i == y_pr_i:
            acc += 1
    return acc/y.shape[0]

In [91]:
Accuracy(y, calc_pred(W, X_st))

1.0

In [92]:
Accuracy(y, y_pr)

0.7

In [101]:
def Confusion_Matrix(y, y_pr, prn = False):
    tp = tn = fp = fn = 0
    for y_i, y_pr_i in zip(y, y_pr):
        if y_pr_i == 1:
            if y_i == y_pr_i:
                tp += 1
            else:
                fp += 1
        else:
            if y_i == y_pr_i:
                tn += 1
            else:
                fn += 1

    if prn:
        print("\ty=1\ty=0")
        print("f=1\t{}\t{}".format(tp, fp))
        print("f=0\t{}\t{}".format(fn, tn))
    else:
        return tp, tn, fp, fn

In [102]:
Confusion_Matrix(y, y_pr, True)

	y=1	y=0
f=1	4	2
f=0	1	3


In [107]:
def Precision(y, y_pr, prn = False):
    tp, tn, fp, fn = Confusion_Matrix(y, y_pr)
    
    precision = tp/(tp + fp)
    
    if prn:
        print("precision = {:.4f}".format(precision))
    else:
        return precision

In [114]:
Precision(y, y_pr, True)

precision = 0.6667


In [115]:
def Recall(y, y_pr, prn = False):
    tp, tn, fp, fn = Confusion_Matrix(y, y_pr)
    
    recall = tp/(tp + fn)
    
    if prn:
        print("recall = {:.4f}".format(recall))
    else:
        return recall

In [117]:
Recall(y, y_pr, True)

recall = 0.8000


In [118]:
def F1(y, y_pr, prn = False):
    precision = Precision(y, y_pr)
    recall = Recall(y, y_pr)
    
    f1 = 2*precision*recall/(precision + recall)
    
    if prn:
        print("f1 score = {:.4f}".format(f1))
    else:
        return f1

In [119]:
F1(y, y_pr, True)

f1 score = 0.7273


## Задание № 6

Могла ли модель переобучиться? Почему?

Моделm может переобучаться т.к. есть корреляция между входными параметрами.

## Задание № 7

Создайте функции eval_model_l1 и eval_model_l2 с применением L1 и L2 регуляризаций соответственно

In [23]:
def eval_model_l1():
    
    return 1

In [24]:
def eval_model_l2():
    
    return 1